<a href="https://colab.research.google.com/github/toast-ceo/Lab_Room/blob/main/VGG_step10_epoch50(Adagrad%26binary_crossentropy).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# vgg 19 훈련

from google.colab import drive
drive.mount('face550_step')
import tensorflow as tf
import numpy as np
import keras
import cv2

from keras.applications.vgg19 import VGG19
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.convolutional import Conv2D
from keras.layers.convolutional import MaxPooling2D
from keras.preprocessing.image import ImageDataGenerator
from sklearn.model_selection import train_test_split


Mounted at face550_step


In [2]:
numberOfClass = 30
pictureWeightHeightSize = 224

train_datagen = ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_directory(
        '/content/face550_step/MyDrive/face550_step/step10_train/',
        target_size=(pictureWeightHeightSize, pictureWeightHeightSize),
        batch_size=numberOfClass,
        class_mode='categorical')

test_datagen = ImageDataGenerator(rescale=1./255)

test_generator = test_datagen.flow_from_directory(
        '/content/face550_step/MyDrive/face550_step/step1_test/',
        target_size=(pictureWeightHeightSize, pictureWeightHeightSize),    
        batch_size=numberOfClass,
        class_mode='categorical')

Found 50 images belonging to 5 classes.
Found 10 images belonging to 5 classes.


In [3]:
input_layer = tf.keras.layers.Input(shape=(224, 224, 3))

vgg_block01 = tf.keras.layers.Conv2D(64 , (3,3), padding= 'SAME', activation="relu")(input_layer)
vgg_block01 = tf.keras.layers.Conv2D(64 , (3,3), padding= 'SAME', activation="relu")(vgg_block01)
vgg_block01 = tf.keras.layers.MaxPool2D((2,2))(vgg_block01)


vgg_block02 = tf.keras.layers.Conv2D(128 , (3,3), padding= 'SAME', activation="relu")(vgg_block01)
vgg_block02 = tf.keras.layers.Conv2D(128, (3,3), padding= 'SAME', activation="relu")(vgg_block02)
vgg_block02 = tf.keras.layers.MaxPool2D((2,2))(vgg_block02)


vgg_block03 = tf.keras.layers.Conv2D(256, (3,3), padding= 'SAME', activation="relu")(vgg_block02)
vgg_block03 = tf.keras.layers.Conv2D(256, (3,3), padding= 'SAME', activation="relu")(vgg_block03)
vgg_block03 = tf.keras.layers.Conv2D(256, (3,3), padding= 'SAME', activation="relu")(vgg_block03)
vgg_block03 = tf.keras.layers.MaxPool2D((2,2))(vgg_block03)

vgg_block04 = tf.keras.layers.Conv2D(512, (3,3), padding= 'SAME', activation="relu")(vgg_block03)
vgg_block04 = tf.keras.layers.Conv2D(512, (3,3), padding= 'SAME', activation="relu")(vgg_block04)
vgg_block04 = tf.keras.layers.Conv2D(512, (3,3), padding= 'SAME', activation="relu")(vgg_block04)
vgg_block04 = tf.keras.layers.MaxPool2D((2,2))(vgg_block04)

vgg_block05 = tf.keras.layers.Conv2D(512, (3,3), padding= 'SAME', activation="relu")(vgg_block04)
vgg_block05 = tf.keras.layers.Conv2D(512, (3,3), padding= 'SAME', activation="relu")(vgg_block05)
vgg_block05 = tf.keras.layers.Conv2D(512, (3,3), padding= 'SAME', activation="relu")(vgg_block05)
vgg_block05 = tf.keras.layers.MaxPool2D((2,2))(vgg_block05)


In [4]:
flatten = tf.keras.layers.Flatten()(vgg_block05)
dense01 = tf.keras.layers.Dense(512, activation='relu')(flatten)
output = tf.keras.layers.Dense(5, activation='softmax')(dense01)

In [5]:

model = tf.keras.models.Model(input_layer, output)


In [6]:
model.compile(optimizer='Adagrad', loss='categorical_crossentropy', metrics=['accuracy'])
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 224, 224, 3)]     0         
_________________________________________________________________
conv2d (Conv2D)              (None, 224, 224, 64)      1792      
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 224, 224, 64)      36928     
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 112, 112, 64)      0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 112, 112, 128)     73856     
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 112, 112, 128)     147584    
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 56, 56, 128)       0     

In [7]:
model.fit(train_generator, epochs=50, validation_data=test_generator)

Epoch 1/50
2/2 [==============================] - 107s 64s/step - loss: 1.6094 - accuracy: 0.0600 - val_loss: 1.6089 - val_accuracy: 0.4000
Epoch 2/50
2/2 [==============================] - 99s 42s/step - loss: 1.6089 - accuracy: 0.4400 - val_loss: 1.6086 - val_accuracy: 0.4000
Epoch 3/50
2/2 [==============================] - 98s 60s/step - loss: 1.6088 - accuracy: 0.3000 - val_loss: 1.6084 - val_accuracy: 0.4000
Epoch 4/50
2/2 [==============================] - 98s 42s/step - loss: 1.6085 - accuracy: 0.4200 - val_loss: 1.6083 - val_accuracy: 0.6000
Epoch 5/50
2/2 [==============================] - 98s 61s/step - loss: 1.6083 - accuracy: 0.4200 - val_loss: 1.6081 - val_accuracy: 0.6000
Epoch 6/50
2/2 [==============================] - 97s 60s/step - loss: 1.6083 - accuracy: 0.4600 - val_loss: 1.6080 - val_accuracy: 0.6000
Epoch 7/50
2/2 [==============================] - 98s 42s/step - loss: 1.6082 - accuracy: 0.6000 - val_loss: 1.6079 - val_accuracy: 0.5000
Epoch 8/50
2/2 [==========

In [8]:
print("-- Evaluate --")
scores = model.evaluate(test_generator)
print("%s: %.2f%%" %(model.metrics_names[1], scores[1]*100))

-- Evaluate --
1/1 [==============================] - 5s 5s/step - loss: 1.6055 - accuracy: 1.0000
accuracy: 100.00%


In [9]:
print("-- Predict --")
output = model.predict(test_generator)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print(test_generator.class_indices)
print(output)

-- Predict --
{'0': 0, '1': 1, '2': 2, '3': 3, '4': 4}
[[0.201 0.200 0.200 0.200 0.199]
 [0.199 0.200 0.200 0.200 0.201]
 [0.199 0.200 0.201 0.200 0.200]
 [0.200 0.201 0.200 0.200 0.200]
 [0.201 0.200 0.200 0.200 0.199]
 [0.199 0.200 0.201 0.200 0.200]
 [0.200 0.201 0.200 0.200 0.200]
 [0.200 0.200 0.200 0.201 0.199]
 [0.199 0.200 0.200 0.201 0.199]
 [0.199 0.200 0.200 0.200 0.201]]


In [10]:
for i in range(0, 10):
  print("Result:", i+1)
  print(output[i])
  print("\n")

Result: 1
[0.201 0.200 0.200 0.200 0.199]


Result: 2
[0.199 0.200 0.200 0.200 0.201]


Result: 3
[0.199 0.200 0.201 0.200 0.200]


Result: 4
[0.200 0.201 0.200 0.200 0.200]


Result: 5
[0.201 0.200 0.200 0.200 0.199]


Result: 6
[0.199 0.200 0.201 0.200 0.200]


Result: 7
[0.200 0.201 0.200 0.200 0.200]


Result: 8
[0.200 0.200 0.200 0.201 0.199]


Result: 9
[0.199 0.200 0.200 0.201 0.199]


Result: 10
[0.199 0.200 0.200 0.200 0.201]


