<a href="https://colab.research.google.com/github/toast-ceo/Lab_Room/blob/main/VGG_step10_epoch100(SGD%26_categorical_crossentropy)_10People.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# vgg 19 훈련

from google.colab import drive
drive.mount('face550_step')
import tensorflow as tf
import numpy as np
import keras
import cv2

from keras.applications.vgg19 import VGG19
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.convolutional import Conv2D
from keras.layers.convolutional import MaxPooling2D
from keras.preprocessing.image import ImageDataGenerator
from sklearn.model_selection import train_test_split


Mounted at face550_step


In [2]:
numberOfClass = 30
pictureWeightHeightSize = 224

train_datagen = ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_directory(
        '/content/face550_step/MyDrive/face550_step/step10_train/',
        target_size=(pictureWeightHeightSize, pictureWeightHeightSize),
        batch_size=numberOfClass,
        class_mode='categorical')

test_datagen = ImageDataGenerator(rescale=1./255)

test_generator = test_datagen.flow_from_directory(
        '/content/face550_step/MyDrive/face550_step/step10_test/',
        target_size=(pictureWeightHeightSize, pictureWeightHeightSize),    
        batch_size=numberOfClass,
        class_mode='categorical')

Found 100 images belonging to 10 classes.
Found 20 images belonging to 10 classes.


In [3]:
input_layer = tf.keras.layers.Input(shape=(224, 224, 3))

vgg_block01 = tf.keras.layers.Conv2D(64 , (3,3), padding= 'SAME', activation="relu")(input_layer)
vgg_block01 = tf.keras.layers.Conv2D(64 , (3,3), padding= 'SAME', activation="relu")(vgg_block01)
vgg_block01 = tf.keras.layers.MaxPool2D((2,2))(vgg_block01)


vgg_block02 = tf.keras.layers.Conv2D(128 , (3,3), padding= 'SAME', activation="relu")(vgg_block01)
vgg_block02 = tf.keras.layers.Conv2D(128, (3,3), padding= 'SAME', activation="relu")(vgg_block02)
vgg_block02 = tf.keras.layers.MaxPool2D((2,2))(vgg_block02)


vgg_block03 = tf.keras.layers.Conv2D(256, (3,3), padding= 'SAME', activation="relu")(vgg_block02)
vgg_block03 = tf.keras.layers.Conv2D(256, (3,3), padding= 'SAME', activation="relu")(vgg_block03)
vgg_block03 = tf.keras.layers.Conv2D(256, (3,3), padding= 'SAME', activation="relu")(vgg_block03)
vgg_block03 = tf.keras.layers.MaxPool2D((2,2))(vgg_block03)

vgg_block04 = tf.keras.layers.Conv2D(512, (3,3), padding= 'SAME', activation="relu")(vgg_block03)
vgg_block04 = tf.keras.layers.Conv2D(512, (3,3), padding= 'SAME', activation="relu")(vgg_block04)
vgg_block04 = tf.keras.layers.Conv2D(512, (3,3), padding= 'SAME', activation="relu")(vgg_block04)
vgg_block04 = tf.keras.layers.MaxPool2D((2,2))(vgg_block04)

vgg_block05 = tf.keras.layers.Conv2D(512, (3,3), padding= 'SAME', activation="relu")(vgg_block04)
vgg_block05 = tf.keras.layers.Conv2D(512, (3,3), padding= 'SAME', activation="relu")(vgg_block05)
vgg_block05 = tf.keras.layers.Conv2D(512, (3,3), padding= 'SAME', activation="relu")(vgg_block05)
vgg_block05 = tf.keras.layers.MaxPool2D((2,2))(vgg_block05)


In [4]:
flatten = tf.keras.layers.Flatten()(vgg_block05)
dense01 = tf.keras.layers.Dense(512, activation='relu')(flatten)
output = tf.keras.layers.Dense(10, activation='softmax')(dense01)

In [5]:

model = tf.keras.models.Model(input_layer, output)


In [6]:
model.compile(optimizer='SGD', loss='categorical_crossentropy', metrics=['accuracy'])
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 224, 224, 3)]     0         
_________________________________________________________________
conv2d (Conv2D)              (None, 224, 224, 64)      1792      
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 224, 224, 64)      36928     
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 112, 112, 64)      0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 112, 112, 128)     73856     
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 112, 112, 128)     147584    
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 56, 56, 128)       0     

In [7]:
model.fit(train_generator, epochs=100, validation_data=test_generator)

Epoch 1/100
4/4 [==============================] - 146s 32s/step - loss: 2.3026 - accuracy: 0.1000 - val_loss: 2.3017 - val_accuracy: 0.1000
Epoch 2/100
4/4 [==============================] - 120s 29s/step - loss: 2.3018 - accuracy: 0.1000 - val_loss: 2.3010 - val_accuracy: 0.2000
Epoch 3/100
4/4 [==============================] - 121s 29s/step - loss: 2.3014 - accuracy: 0.2100 - val_loss: 2.3007 - val_accuracy: 0.4000
Epoch 4/100
4/4 [==============================] - 123s 29s/step - loss: 2.3010 - accuracy: 0.1700 - val_loss: 2.3005 - val_accuracy: 0.1000
Epoch 5/100
4/4 [==============================] - 121s 29s/step - loss: 2.3008 - accuracy: 0.1000 - val_loss: 2.3000 - val_accuracy: 0.1000
Epoch 6/100
4/4 [==============================] - 121s 29s/step - loss: 2.3003 - accuracy: 0.1200 - val_loss: 2.2996 - val_accuracy: 0.3000
Epoch 7/100
4/4 [==============================] - 122s 29s/step - loss: 2.3001 - accuracy: 0.2800 - val_loss: 2.2994 - val_accuracy: 0.2000
Epoch 8/100
4

In [8]:
print("-- Evaluate --")
scores = model.evaluate(test_generator)
print("%s: %.2f%%" %(model.metrics_names[1], scores[1]*100))

-- Evaluate --
1/1 [==============================] - 6s 6s/step - loss: 5.3096e-04 - accuracy: 1.0000
accuracy: 100.00%


In [9]:
print("-- Predict --")
output = model.predict(test_generator)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print(test_generator.class_indices)
print(output)

-- Predict --
{'0': 0, '1': 1, '2': 2, '3': 3, '4': 4, '5': 5, '6': 6, '7': 7, '8': 8, '9': 9}
[[0.000 0.000 0.000 1.000 0.000 0.000 0.000 0.000 0.000 0.000]
 [0.000 0.000 0.000 0.000 0.000 1.000 0.000 0.000 0.000 0.000]
 [0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 1.000]
 [0.000 0.000 1.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000]
 [0.000 0.000 0.000 0.000 0.000 1.000 0.000 0.000 0.000 0.000]
 [0.000 0.000 0.000 0.000 0.000 0.000 0.999 0.000 0.000 0.000]
 [0.000 0.000 0.000 0.000 1.000 0.000 0.000 0.000 0.000 0.000]
 [0.000 0.000 0.000 0.000 0.000 0.000 0.000 1.000 0.000 0.000]
 [0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 1.000]
 [0.000 0.000 0.000 0.000 1.000 0.000 0.000 0.000 0.000 0.000]
 [0.000 0.000 0.000 0.000 0.000 0.000 0.000 1.000 0.000 0.000]
 [0.000 0.000 0.000 0.000 0.000 0.000 0.004 0.000 0.995 0.000]
 [0.000 0.000 0.000 0.000 0.000 0.000 0.004 0.000 0.996 0.000]
 [0.000 0.000 1.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000]
 [0.000 0.000 0.000 1.0

In [10]:
for i in range(0, 10):
  print("Result:", i+1)
  print(output[i])
  print("\n")

Result: 1
[0.000 0.000 0.000 1.000 0.000 0.000 0.000 0.000 0.000 0.000]


Result: 2
[0.000 0.000 0.000 0.000 0.000 1.000 0.000 0.000 0.000 0.000]


Result: 3
[0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 1.000]


Result: 4
[0.000 0.000 1.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000]


Result: 5
[0.000 0.000 0.000 0.000 0.000 1.000 0.000 0.000 0.000 0.000]


Result: 6
[0.000 0.000 0.000 0.000 0.000 0.000 0.999 0.000 0.000 0.000]


Result: 7
[0.000 0.000 0.000 0.000 1.000 0.000 0.000 0.000 0.000 0.000]


Result: 8
[0.000 0.000 0.000 0.000 0.000 0.000 0.000 1.000 0.000 0.000]


Result: 9
[0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 1.000]


Result: 10
[0.000 0.000 0.000 0.000 1.000 0.000 0.000 0.000 0.000 0.000]


