<a href="https://colab.research.google.com/github/toast-ceo/Lab_Room/blob/main/VGG_step10_epoch50(SGD%26categorical_crossentropy).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# vgg 19 훈련

from google.colab import drive
drive.mount('face550_step')
import tensorflow as tf
import numpy as np
import keras
import cv2

from keras.applications.vgg19 import VGG19
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.convolutional import Conv2D
from keras.layers.convolutional import MaxPooling2D
from keras.preprocessing.image import ImageDataGenerator
from sklearn.model_selection import train_test_split


Mounted at face550_step


In [2]:
numberOfClass = 30
pictureWeightHeightSize = 224

train_datagen = ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_directory(
        '/content/face550_step/MyDrive/face550_step/step10_train/',
        target_size=(pictureWeightHeightSize, pictureWeightHeightSize),
        batch_size=numberOfClass,
        class_mode='categorical')

test_datagen = ImageDataGenerator(rescale=1./255)

test_generator = test_datagen.flow_from_directory(
        '/content/face550_step/MyDrive/face550_step/step1_test/',
        target_size=(pictureWeightHeightSize, pictureWeightHeightSize),    
        batch_size=numberOfClass,
        class_mode='categorical')

Found 50 images belonging to 5 classes.
Found 10 images belonging to 5 classes.


In [3]:
input_layer = tf.keras.layers.Input(shape=(224, 224, 3))

vgg_block01 = tf.keras.layers.Conv2D(64 , (3,3), padding= 'SAME', activation="relu")(input_layer)
vgg_block01 = tf.keras.layers.Conv2D(64 , (3,3), padding= 'SAME', activation="relu")(vgg_block01)
vgg_block01 = tf.keras.layers.MaxPool2D((2,2))(vgg_block01)


vgg_block02 = tf.keras.layers.Conv2D(128 , (3,3), padding= 'SAME', activation="relu")(vgg_block01)
vgg_block02 = tf.keras.layers.Conv2D(128, (3,3), padding= 'SAME', activation="relu")(vgg_block02)
vgg_block02 = tf.keras.layers.MaxPool2D((2,2))(vgg_block02)


vgg_block03 = tf.keras.layers.Conv2D(256, (3,3), padding= 'SAME', activation="relu")(vgg_block02)
vgg_block03 = tf.keras.layers.Conv2D(256, (3,3), padding= 'SAME', activation="relu")(vgg_block03)
vgg_block03 = tf.keras.layers.Conv2D(256, (3,3), padding= 'SAME', activation="relu")(vgg_block03)
vgg_block03 = tf.keras.layers.MaxPool2D((2,2))(vgg_block03)

vgg_block04 = tf.keras.layers.Conv2D(512, (3,3), padding= 'SAME', activation="relu")(vgg_block03)
vgg_block04 = tf.keras.layers.Conv2D(512, (3,3), padding= 'SAME', activation="relu")(vgg_block04)
vgg_block04 = tf.keras.layers.Conv2D(512, (3,3), padding= 'SAME', activation="relu")(vgg_block04)
vgg_block04 = tf.keras.layers.MaxPool2D((2,2))(vgg_block04)

vgg_block05 = tf.keras.layers.Conv2D(512, (3,3), padding= 'SAME', activation="relu")(vgg_block04)
vgg_block05 = tf.keras.layers.Conv2D(512, (3,3), padding= 'SAME', activation="relu")(vgg_block05)
vgg_block05 = tf.keras.layers.Conv2D(512, (3,3), padding= 'SAME', activation="relu")(vgg_block05)
vgg_block05 = tf.keras.layers.MaxPool2D((2,2))(vgg_block05)


In [4]:
flatten = tf.keras.layers.Flatten()(vgg_block05)
dense01 = tf.keras.layers.Dense(512, activation='relu')(flatten)
output = tf.keras.layers.Dense(5, activation='softmax')(dense01)

In [5]:

model = tf.keras.models.Model(input_layer, output)


In [6]:
model.compile(optimizer='SGD', loss='categorical_crossentropy', metrics=['accuracy'])
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 224, 224, 3)]     0         
_________________________________________________________________
conv2d (Conv2D)              (None, 224, 224, 64)      1792      
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 224, 224, 64)      36928     
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 112, 112, 64)      0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 112, 112, 128)     73856     
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 112, 112, 128)     147584    
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 56, 56, 128)       0     

In [7]:
model.fit(train_generator, epochs=50, validation_data=test_generator)

Epoch 1/50
2/2 [==============================] - 76s 43s/step - loss: 1.6092 - accuracy: 0.2000 - val_loss: 1.6081 - val_accuracy: 0.4000
Epoch 2/50
2/2 [==============================] - 62s 38s/step - loss: 1.6080 - accuracy: 0.5000 - val_loss: 1.6074 - val_accuracy: 0.4000
Epoch 3/50
2/2 [==============================] - 61s 38s/step - loss: 1.6078 - accuracy: 0.2600 - val_loss: 1.6068 - val_accuracy: 0.6000
Epoch 4/50
2/2 [==============================] - 61s 26s/step - loss: 1.6068 - accuracy: 0.6000 - val_loss: 1.6064 - val_accuracy: 0.4000
Epoch 5/50
2/2 [==============================] - 62s 39s/step - loss: 1.6071 - accuracy: 0.2800 - val_loss: 1.6060 - val_accuracy: 0.6000
Epoch 6/50
2/2 [==============================] - 61s 37s/step - loss: 1.6062 - accuracy: 0.8200 - val_loss: 1.6055 - val_accuracy: 1.0000
Epoch 7/50
2/2 [==============================] - 61s 38s/step - loss: 1.6062 - accuracy: 0.5600 - val_loss: 1.6051 - val_accuracy: 1.0000
Epoch 8/50
2/2 [===========

In [8]:
print("-- Evaluate --")
scores = model.evaluate(test_generator)
print("%s: %.2f%%" %(model.metrics_names[1], scores[1]*100))

-- Evaluate --
1/1 [==============================] - 3s 3s/step - loss: 1.5623 - accuracy: 1.0000
accuracy: 100.00%


In [9]:
print("-- Predict --")
output = model.predict(test_generator)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print(test_generator.class_indices)
print(output)

-- Predict --
{'0': 0, '1': 1, '2': 2, '3': 3, '4': 4}
[[0.218 0.196 0.197 0.202 0.187]
 [0.200 0.205 0.200 0.204 0.191]
 [0.197 0.200 0.206 0.204 0.193]
 [0.218 0.196 0.197 0.202 0.186]
 [0.194 0.200 0.198 0.202 0.207]
 [0.197 0.200 0.206 0.204 0.193]
 [0.199 0.198 0.199 0.213 0.191]
 [0.194 0.200 0.198 0.202 0.207]
 [0.199 0.198 0.199 0.213 0.191]
 [0.200 0.205 0.200 0.204 0.191]]


In [10]:
for i in range(0, 10):
  print("Result:", i+1)
  print(output[i])
  print("\n")

Result: 1
[0.218 0.196 0.197 0.202 0.187]


Result: 2
[0.200 0.205 0.200 0.204 0.191]


Result: 3
[0.197 0.200 0.206 0.204 0.193]


Result: 4
[0.218 0.196 0.197 0.202 0.186]


Result: 5
[0.194 0.200 0.198 0.202 0.207]


Result: 6
[0.197 0.200 0.206 0.204 0.193]


Result: 7
[0.199 0.198 0.199 0.213 0.191]


Result: 8
[0.194 0.200 0.198 0.202 0.207]


Result: 9
[0.199 0.198 0.199 0.213 0.191]


Result: 10
[0.200 0.205 0.200 0.204 0.191]


