<a href="https://colab.research.google.com/github/toast-ceo/Lab_Room/blob/main/face550_step1_epoch10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
# vgg 19 훈련

from google.colab import drive
drive.mount('face550_step')
import tensorflow as tf
import numpy as np
import keras
import cv2

from keras.applications.vgg19 import VGG19
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.convolutional import Conv2D
from keras.layers.convolutional import MaxPooling2D
from keras.preprocessing.image import ImageDataGenerator
from sklearn.model_selection import train_test_split


Drive already mounted at face550_step; to attempt to forcibly remount, call drive.mount("face550_step", force_remount=True).


In [23]:
numberOfClass = 30
pictureWeightHeightSize = 224

train_datagen = ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_directory(
        '/content/face550_step/MyDrive/face550_step/step1_train/',
        target_size=(pictureWeightHeightSize, pictureWeightHeightSize),
        batch_size=numberOfClass,
        class_mode='categorical')

test_datagen = ImageDataGenerator(rescale=1./255)

test_generator = test_datagen.flow_from_directory(
        '/content/face550_step/MyDrive/face550_step/step1_test/',
        target_size=(pictureWeightHeightSize, pictureWeightHeightSize),    
        batch_size=numberOfClass,
        class_mode='categorical')

Found 50 images belonging to 5 classes.
Found 10 images belonging to 5 classes.


In [24]:
input_layer = tf.keras.layers.Input(shape=(224, 224, 3))

vgg_block01 = tf.keras.layers.Conv2D(64 , (3,3), padding= 'SAME', activation="relu")(input_layer)
vgg_block01 = tf.keras.layers.Conv2D(64 , (3,3), padding= 'SAME', activation="relu")(vgg_block01)
vgg_block01 = tf.keras.layers.MaxPool2D((2,2))(vgg_block01)


vgg_block02 = tf.keras.layers.Conv2D(128 , (3,3), padding= 'SAME', activation="relu")(vgg_block01)
vgg_block02 = tf.keras.layers.Conv2D(128, (3,3), padding= 'SAME', activation="relu")(vgg_block02)
vgg_block02 = tf.keras.layers.MaxPool2D((2,2))(vgg_block02)


vgg_block03 = tf.keras.layers.Conv2D(256, (3,3), padding= 'SAME', activation="relu")(vgg_block02)
vgg_block03 = tf.keras.layers.Conv2D(256, (3,3), padding= 'SAME', activation="relu")(vgg_block03)
vgg_block03 = tf.keras.layers.Conv2D(256, (3,3), padding= 'SAME', activation="relu")(vgg_block03)
vgg_block03 = tf.keras.layers.MaxPool2D((2,2))(vgg_block03)

vgg_block04 = tf.keras.layers.Conv2D(512, (3,3), padding= 'SAME', activation="relu")(vgg_block03)
vgg_block04 = tf.keras.layers.Conv2D(512, (3,3), padding= 'SAME', activation="relu")(vgg_block04)
vgg_block04 = tf.keras.layers.Conv2D(512, (3,3), padding= 'SAME', activation="relu")(vgg_block04)
vgg_block04 = tf.keras.layers.MaxPool2D((2,2))(vgg_block04)

vgg_block05 = tf.keras.layers.Conv2D(512, (3,3), padding= 'SAME', activation="relu")(vgg_block04)
vgg_block05 = tf.keras.layers.Conv2D(512, (3,3), padding= 'SAME', activation="relu")(vgg_block05)
vgg_block05 = tf.keras.layers.Conv2D(512, (3,3), padding= 'SAME', activation="relu")(vgg_block05)
vgg_block05 = tf.keras.layers.MaxPool2D((2,2))(vgg_block05)


In [28]:
flatten = tf.keras.layers.Flatten()(vgg_block05)
dense01 = tf.keras.layers.Dense(512, activation='relu')(flatten)
output = tf.keras.layers.Dense(5, activation='softmax')(dense01)

In [29]:

model = tf.keras.models.Model(input_layer, output)


In [30]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.summary()

Model: "model_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_5 (InputLayer)         [(None, 224, 224, 3)]     0         
_________________________________________________________________
conv2d_49 (Conv2D)           (None, 224, 224, 64)      1792      
_________________________________________________________________
conv2d_50 (Conv2D)           (None, 224, 224, 64)      36928     
_________________________________________________________________
max_pooling2d_19 (MaxPooling (None, 112, 112, 64)      0         
_________________________________________________________________
conv2d_51 (Conv2D)           (None, 112, 112, 128)     73856     
_________________________________________________________________
conv2d_52 (Conv2D)           (None, 112, 112, 128)     147584    
_________________________________________________________________
max_pooling2d_20 (MaxPooling (None, 56, 56, 128)       0   

In [31]:
model.fit(train_generator, epochs=10, validation_data=test_generator)

Epoch 1/10
2/2 [==============================] - 78s 35s/step - loss: 2.9734 - accuracy: 0.2000 - val_loss: 1.6095 - val_accuracy: 0.2000
Epoch 2/10
2/2 [==============================] - 70s 43s/step - loss: 1.6109 - accuracy: 0.2000 - val_loss: 1.6099 - val_accuracy: 0.2000
Epoch 3/10
2/2 [==============================] - 71s 44s/step - loss: 1.6120 - accuracy: 0.1000 - val_loss: 1.6096 - val_accuracy: 0.2000
Epoch 4/10
2/2 [==============================] - 71s 44s/step - loss: 1.6142 - accuracy: 0.2000 - val_loss: 1.6102 - val_accuracy: 0.2000
Epoch 5/10
2/2 [==============================] - 70s 30s/step - loss: 1.6105 - accuracy: 0.2000 - val_loss: 1.6098 - val_accuracy: 0.2000
Epoch 6/10
2/2 [==============================] - 70s 43s/step - loss: 1.6105 - accuracy: 0.2000 - val_loss: 1.6098 - val_accuracy: 0.2000
Epoch 7/10
2/2 [==============================] - 71s 30s/step - loss: 1.6094 - accuracy: 0.2000 - val_loss: 1.6097 - val_accuracy: 0.2000
Epoch 8/10
2/2 [===========

In [32]:
print("-- Evaluate --")
scores = model.evaluate(test_generator)
print("%s: %.2f%%" %(model.metrics_names[1], scores[1]*100))

-- Evaluate --
1/1 [==============================] - 3s 3s/step - loss: 1.6192 - accuracy: 0.2000
accuracy: 20.00%


In [34]:
print("-- Predict --")
output = model.predict(test_generator)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print(test_generator.class_indices)
print(output)

-- Predict --
{'0': 0, '1': 1, '2': 2, '3': 3, '4': 4}
[[0.199 0.202 0.206 0.193 0.201]
 [0.196 0.202 0.217 0.183 0.201]
 [0.201 0.199 0.212 0.186 0.202]
 [0.199 0.202 0.203 0.195 0.201]
 [0.197 0.202 0.217 0.183 0.201]
 [0.201 0.199 0.212 0.186 0.202]
 [0.199 0.202 0.206 0.193 0.201]
 [0.199 0.202 0.207 0.192 0.200]
 [0.199 0.202 0.207 0.192 0.200]
 [0.199 0.202 0.203 0.195 0.201]]


In [37]:
for i in range(0, 10):
  print("Result:", i+1)
  print(output[i])
  print("\n")

Result: 1
[0.199 0.202 0.206 0.193 0.201]


Result: 2
[0.196 0.202 0.217 0.183 0.201]


Result: 3
[0.201 0.199 0.212 0.186 0.202]


Result: 4
[0.199 0.202 0.203 0.195 0.201]


Result: 5
[0.197 0.202 0.217 0.183 0.201]


Result: 6
[0.201 0.199 0.212 0.186 0.202]


Result: 7
[0.199 0.202 0.206 0.193 0.201]


Result: 8
[0.199 0.202 0.207 0.192 0.200]


Result: 9
[0.199 0.202 0.207 0.192 0.200]


Result: 10
[0.199 0.202 0.203 0.195 0.201]


