<a href="https://colab.research.google.com/github/toast-ceo/Lab_Room/blob/main/VGG_step10_epoch100_(Adam%26binary_crossentropy).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# vgg 19 훈련

from google.colab import drive
drive.mount('face550_step')
import tensorflow as tf
import numpy as np
import keras
import cv2

from keras.applications.vgg19 import VGG19
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.convolutional import Conv2D
from keras.layers.convolutional import MaxPooling2D
from keras.preprocessing.image import ImageDataGenerator
from sklearn.model_selection import train_test_split


Mounted at face550_step


In [2]:
numberOfClass = 30
pictureWeightHeightSize = 224

train_datagen = ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_directory(
        '/content/face550_step/MyDrive/face550_step/step10_train/',
        target_size=(pictureWeightHeightSize, pictureWeightHeightSize),
        batch_size=numberOfClass,
        class_mode='categorical')

test_datagen = ImageDataGenerator(rescale=1./255)

test_generator = test_datagen.flow_from_directory(
        '/content/face550_step/MyDrive/face550_step/step1_test/',
        target_size=(pictureWeightHeightSize, pictureWeightHeightSize),    
        batch_size=numberOfClass,
        class_mode='categorical')

Found 50 images belonging to 5 classes.
Found 10 images belonging to 5 classes.


In [3]:
input_layer = tf.keras.layers.Input(shape=(224, 224, 3))

vgg_block01 = tf.keras.layers.Conv2D(64 , (3,3), padding= 'SAME', activation="relu")(input_layer)
vgg_block01 = tf.keras.layers.Conv2D(64 , (3,3), padding= 'SAME', activation="relu")(vgg_block01)
vgg_block01 = tf.keras.layers.MaxPool2D((2,2))(vgg_block01)


vgg_block02 = tf.keras.layers.Conv2D(128 , (3,3), padding= 'SAME', activation="relu")(vgg_block01)
vgg_block02 = tf.keras.layers.Conv2D(128, (3,3), padding= 'SAME', activation="relu")(vgg_block02)
vgg_block02 = tf.keras.layers.MaxPool2D((2,2))(vgg_block02)


vgg_block03 = tf.keras.layers.Conv2D(256, (3,3), padding= 'SAME', activation="relu")(vgg_block02)
vgg_block03 = tf.keras.layers.Conv2D(256, (3,3), padding= 'SAME', activation="relu")(vgg_block03)
vgg_block03 = tf.keras.layers.Conv2D(256, (3,3), padding= 'SAME', activation="relu")(vgg_block03)
vgg_block03 = tf.keras.layers.MaxPool2D((2,2))(vgg_block03)

vgg_block04 = tf.keras.layers.Conv2D(512, (3,3), padding= 'SAME', activation="relu")(vgg_block03)
vgg_block04 = tf.keras.layers.Conv2D(512, (3,3), padding= 'SAME', activation="relu")(vgg_block04)
vgg_block04 = tf.keras.layers.Conv2D(512, (3,3), padding= 'SAME', activation="relu")(vgg_block04)
vgg_block04 = tf.keras.layers.MaxPool2D((2,2))(vgg_block04)

vgg_block05 = tf.keras.layers.Conv2D(512, (3,3), padding= 'SAME', activation="relu")(vgg_block04)
vgg_block05 = tf.keras.layers.Conv2D(512, (3,3), padding= 'SAME', activation="relu")(vgg_block05)
vgg_block05 = tf.keras.layers.Conv2D(512, (3,3), padding= 'SAME', activation="relu")(vgg_block05)
vgg_block05 = tf.keras.layers.MaxPool2D((2,2))(vgg_block05)


In [4]:
flatten = tf.keras.layers.Flatten()(vgg_block05)
dense01 = tf.keras.layers.Dense(512, activation='relu')(flatten)
output = tf.keras.layers.Dense(5, activation='softmax')(dense01)

In [5]:

model = tf.keras.models.Model(input_layer, output)


In [6]:
model.compile(optimizer='Adam', loss='binary_crossentropy', metrics=['accuracy'])
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 224, 224, 3)]     0         
_________________________________________________________________
conv2d (Conv2D)              (None, 224, 224, 64)      1792      
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 224, 224, 64)      36928     
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 112, 112, 64)      0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 112, 112, 128)     73856     
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 112, 112, 128)     147584    
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 56, 56, 128)       0     

In [7]:
model.fit(train_generator, epochs=50, validation_data=test_generator)

Epoch 1/50
2/2 [==============================] - 107s 62s/step - loss: 0.7442 - accuracy: 0.2000 - val_loss: 0.6937 - val_accuracy: 0.2000
Epoch 2/50
2/2 [==============================] - 95s 59s/step - loss: 0.6917 - accuracy: 0.2000 - val_loss: 0.6769 - val_accuracy: 0.2000
Epoch 3/50
2/2 [==============================] - 96s 41s/step - loss: 0.6200 - accuracy: 0.2000 - val_loss: 4.3029 - val_accuracy: 0.2000
Epoch 4/50
2/2 [==============================] - 95s 59s/step - loss: 1.9324 - accuracy: 0.2000 - val_loss: 0.6492 - val_accuracy: 0.2000
Epoch 5/50
2/2 [==============================] - 95s 41s/step - loss: 0.6600 - accuracy: 0.2000 - val_loss: 0.6805 - val_accuracy: 0.2000
Epoch 6/50
2/2 [==============================] - 95s 41s/step - loss: 0.6814 - accuracy: 0.2000 - val_loss: 0.6831 - val_accuracy: 0.2000
Epoch 7/50
2/2 [==============================] - 95s 59s/step - loss: 0.6829 - accuracy: 0.2000 - val_loss: 0.6810 - val_accuracy: 0.2000
Epoch 8/50
2/2 [==========

In [8]:
print("-- Evaluate --")
scores = model.evaluate(test_generator)
print("%s: %.2f%%" %(model.metrics_names[1], scores[1]*100))

-- Evaluate --
1/1 [==============================] - 5s 5s/step - loss: 0.5007 - accuracy: 0.2000
accuracy: 20.00%


In [9]:
print("-- Predict --")
output = model.predict(test_generator)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print(test_generator.class_indices)
print(output)

-- Predict --
{'0': 0, '1': 1, '2': 2, '3': 3, '4': 4}
[[0.201 0.187 0.222 0.199 0.191]
 [0.201 0.187 0.222 0.199 0.191]
 [0.201 0.187 0.222 0.199 0.191]
 [0.201 0.187 0.222 0.199 0.191]
 [0.201 0.187 0.222 0.199 0.191]
 [0.201 0.187 0.222 0.199 0.191]
 [0.201 0.187 0.222 0.199 0.191]
 [0.201 0.187 0.222 0.199 0.191]
 [0.201 0.187 0.222 0.199 0.191]
 [0.201 0.187 0.222 0.199 0.191]]


In [10]:
for i in range(0, 10):
  print("Result:", i+1)
  print(output[i])
  print("\n")

Result: 1
[0.201 0.187 0.222 0.199 0.191]


Result: 2
[0.201 0.187 0.222 0.199 0.191]


Result: 3
[0.201 0.187 0.222 0.199 0.191]


Result: 4
[0.201 0.187 0.222 0.199 0.191]


Result: 5
[0.201 0.187 0.222 0.199 0.191]


Result: 6
[0.201 0.187 0.222 0.199 0.191]


Result: 7
[0.201 0.187 0.222 0.199 0.191]


Result: 8
[0.201 0.187 0.222 0.199 0.191]


Result: 9
[0.201 0.187 0.222 0.199 0.191]


Result: 10
[0.201 0.187 0.222 0.199 0.191]


