<a href="https://colab.research.google.com/github/toast-ceo/Lab_Room/blob/main/VGG_step1_epoch100.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
# vgg 19 훈련

from google.colab import drive
drive.mount('face550_step')
import tensorflow as tf
import numpy as np
import keras
import cv2

from keras.applications.vgg19 import VGG19
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.convolutional import Conv2D
from keras.layers.convolutional import MaxPooling2D
from keras.preprocessing.image import ImageDataGenerator
from sklearn.model_selection import train_test_split


Drive already mounted at face550_step; to attempt to forcibly remount, call drive.mount("face550_step", force_remount=True).


In [9]:
numberOfClass = 30
pictureWeightHeightSize = 224

train_datagen = ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_directory(
        '/content/face550_step/MyDrive/face550_step/step1_train/',
        target_size=(pictureWeightHeightSize, pictureWeightHeightSize),
        batch_size=numberOfClass,
        class_mode='categorical')

test_datagen = ImageDataGenerator(rescale=1./255)

test_generator = test_datagen.flow_from_directory(
        '/content/face550_step/MyDrive/face550_step/step1_test/',
        target_size=(pictureWeightHeightSize, pictureWeightHeightSize),    
        batch_size=numberOfClass,
        class_mode='categorical')

Found 50 images belonging to 5 classes.
Found 10 images belonging to 5 classes.


In [10]:
input_layer = tf.keras.layers.Input(shape=(224, 224, 3))

vgg_block01 = tf.keras.layers.Conv2D(64 , (3,3), padding= 'SAME', activation="relu")(input_layer)
vgg_block01 = tf.keras.layers.Conv2D(64 , (3,3), padding= 'SAME', activation="relu")(vgg_block01)
vgg_block01 = tf.keras.layers.MaxPool2D((2,2))(vgg_block01)


vgg_block02 = tf.keras.layers.Conv2D(128 , (3,3), padding= 'SAME', activation="relu")(vgg_block01)
vgg_block02 = tf.keras.layers.Conv2D(128, (3,3), padding= 'SAME', activation="relu")(vgg_block02)
vgg_block02 = tf.keras.layers.MaxPool2D((2,2))(vgg_block02)


vgg_block03 = tf.keras.layers.Conv2D(256, (3,3), padding= 'SAME', activation="relu")(vgg_block02)
vgg_block03 = tf.keras.layers.Conv2D(256, (3,3), padding= 'SAME', activation="relu")(vgg_block03)
vgg_block03 = tf.keras.layers.Conv2D(256, (3,3), padding= 'SAME', activation="relu")(vgg_block03)
vgg_block03 = tf.keras.layers.MaxPool2D((2,2))(vgg_block03)

vgg_block04 = tf.keras.layers.Conv2D(512, (3,3), padding= 'SAME', activation="relu")(vgg_block03)
vgg_block04 = tf.keras.layers.Conv2D(512, (3,3), padding= 'SAME', activation="relu")(vgg_block04)
vgg_block04 = tf.keras.layers.Conv2D(512, (3,3), padding= 'SAME', activation="relu")(vgg_block04)
vgg_block04 = tf.keras.layers.MaxPool2D((2,2))(vgg_block04)

vgg_block05 = tf.keras.layers.Conv2D(512, (3,3), padding= 'SAME', activation="relu")(vgg_block04)
vgg_block05 = tf.keras.layers.Conv2D(512, (3,3), padding= 'SAME', activation="relu")(vgg_block05)
vgg_block05 = tf.keras.layers.Conv2D(512, (3,3), padding= 'SAME', activation="relu")(vgg_block05)
vgg_block05 = tf.keras.layers.MaxPool2D((2,2))(vgg_block05)


In [11]:
flatten = tf.keras.layers.Flatten()(vgg_block05)
dense01 = tf.keras.layers.Dense(512, activation='relu')(flatten)
output = tf.keras.layers.Dense(5, activation='softmax')(dense01)

In [12]:

model = tf.keras.models.Model(input_layer, output)


In [13]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.summary()

Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 224, 224, 3)]     0         
_________________________________________________________________
conv2d_13 (Conv2D)           (None, 224, 224, 64)      1792      
_________________________________________________________________
conv2d_14 (Conv2D)           (None, 224, 224, 64)      36928     
_________________________________________________________________
max_pooling2d_5 (MaxPooling2 (None, 112, 112, 64)      0         
_________________________________________________________________
conv2d_15 (Conv2D)           (None, 112, 112, 128)     73856     
_________________________________________________________________
conv2d_16 (Conv2D)           (None, 112, 112, 128)     147584    
_________________________________________________________________
max_pooling2d_6 (MaxPooling2 (None, 56, 56, 128)       0   

In [14]:
model.fit(train_generator, epochs=100, validation_data=test_generator)

Epoch 1/100
2/2 [==============================] - 90s 38s/step - loss: 3.7288 - accuracy: 0.1800 - val_loss: 1.6095 - val_accuracy: 0.2000
Epoch 2/100
2/2 [==============================] - 85s 37s/step - loss: 1.6117 - accuracy: 0.2000 - val_loss: 1.6096 - val_accuracy: 0.2000
Epoch 3/100
2/2 [==============================] - 85s 53s/step - loss: 1.6102 - accuracy: 0.1600 - val_loss: 1.6095 - val_accuracy: 0.2000
Epoch 4/100
2/2 [==============================] - 85s 53s/step - loss: 1.6103 - accuracy: 0.2000 - val_loss: 1.6095 - val_accuracy: 0.2000
Epoch 5/100
2/2 [==============================] - 85s 53s/step - loss: 1.6099 - accuracy: 0.2000 - val_loss: 1.6095 - val_accuracy: 0.2000
Epoch 6/100
2/2 [==============================] - 85s 37s/step - loss: 1.6101 - accuracy: 0.2000 - val_loss: 1.6095 - val_accuracy: 0.2000
Epoch 7/100
2/2 [==============================] - 85s 53s/step - loss: 1.6095 - accuracy: 0.2000 - val_loss: 1.6095 - val_accuracy: 0.2000
Epoch 8/100
2/2 [===

In [15]:
print("-- Evaluate --")
scores = model.evaluate(test_generator)
print("%s: %.2f%%" %(model.metrics_names[1], scores[1]*100))

-- Evaluate --
1/1 [==============================] - 4s 4s/step - loss: 1.6095 - accuracy: 0.2000
accuracy: 20.00%


In [16]:
print("-- Predict --")
output = model.predict(test_generator)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print(test_generator.class_indices)
print(output)

-- Predict --
{'0': 0, '1': 1, '2': 2, '3': 3, '4': 4}
[[0.201 0.201 0.201 0.198 0.200]
 [0.201 0.201 0.201 0.198 0.200]
 [0.201 0.201 0.201 0.198 0.200]
 [0.201 0.201 0.201 0.198 0.200]
 [0.201 0.201 0.201 0.198 0.200]
 [0.201 0.201 0.201 0.198 0.200]
 [0.201 0.201 0.201 0.198 0.200]
 [0.201 0.201 0.201 0.198 0.200]
 [0.201 0.201 0.201 0.198 0.200]
 [0.201 0.201 0.201 0.198 0.200]]


In [17]:
for i in range(0, 10):
  print("Result:", i+1)
  print(output[i])
  print("\n")

Result: 1
[0.201 0.201 0.201 0.198 0.200]


Result: 2
[0.201 0.201 0.201 0.198 0.200]


Result: 3
[0.201 0.201 0.201 0.198 0.200]


Result: 4
[0.201 0.201 0.201 0.198 0.200]


Result: 5
[0.201 0.201 0.201 0.198 0.200]


Result: 6
[0.201 0.201 0.201 0.198 0.200]


Result: 7
[0.201 0.201 0.201 0.198 0.200]


Result: 8
[0.201 0.201 0.201 0.198 0.200]


Result: 9
[0.201 0.201 0.201 0.198 0.200]


Result: 10
[0.201 0.201 0.201 0.198 0.200]


